### ISSUE TITLE
Elegant Blue v1.1 Members List inconsistency 

### ISSUE THREAD

**Issue by Drflash55** [archnemeziz/Discord#1]
The Member List doesn't match up with the rest of the theme.
![image](https://user-images.githubusercontent.com/13694448/38364328-25f870d0-38a6-11e8-8c8e-82d539f357ad.png)

Could've been because of a recent update that changed how much space is available on the Member List.

Version: 1.1

**Comment by archnemeziz** [comment]
Fixed.
