### ISSUE TITLE
Issue/Bug/Feature - Blocked Messages are Deleted

### ISSUE THREAD

**Issue by ghost** [archnemeziz/Discord#2]
Blocked Messages do not appear at all. They're deleted completely and part of me would love to call it a feature, but I figured it was something that should be mentioned.

https://cdn.discordapp.com/attachments/341087234776236032/431862100764393482/Screenshot_20180406-130518.png

https://cdn.discordapp.com/attachments/341087234776236032/431862079838748673/unknown.png

**Comment by archnemeziz** [comment]
Yup I added that long ago, I prefer it this way since for me blocking someone shouldn't show that they've sent a message at all.
You can undo this using BD's customcss however:
.message-group-blocked {display: inherit;}
