### ISSUE TITLE
Problem with new Discord Update

### ISSUE THREAD

**Issue by Skyway1111** [archnemeziz/Discord#4]
The server chat and the whole bar on the right with members of the server has been changed in the most recent update, also the chat room header has been changed.
![519c2ee6eb5d2062b6b6909cf1391fd1](https://user-images.githubusercontent.com/40695911/43672764-9cadafa2-9769-11e8-93ac-4395887d5980.png)

**Comment by xstefen** [comment]
Nah, this theme is always perfect. Cancel PR

![image](https://user-images.githubusercontent.com/5105153/50862759-1ca7ea00-1362-11e9-9480-09bd84c8ec39.png)

**Comment by archnemeziz** [comment]
This was fixed long ago, didn't notice the report
