### ISSUE TITLE
Not a Issue but I need help

### ISSUE THREAD

**Issue by SerenModz21** [archnemeziz/Discord#5]
how do i install the theme coz there is so many files

**Comment by archnemeziz** [comment]
You only need the ElegantBlue.theme.css file which goes into the betterdiscord themes folder.
The theme still works but there are some broken areas and unfortunately I'm no longer actively updating it. I might do an update at some point but I'm not making any promises as I simply don't have the time any more.

**Comment by SerenModz21** [comment]
i hope u will update it soon
